version: '3'

services:
  kerkuz:
    container_name: archetype
    image: registry-cicd.kerkuz.com/archetype:${TAG}
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:archetype-dev.kerkuz.com
        - traefik.enable=true
        - traefik.port=9018
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http

networks:
  traefik-public:
    external: true
