drop table DIRECCION

CREATE TABLE Region
(
    id_Region NUMBER (10),
    nom_reg VARCHAR2 (50) NOT NULL,
    CONSTRAINT direccion_pk PRIMARY KEY (id_Region)
);

INSERT INTO REGION VALUES(1,'Arica y Parinacota');
INSERT INTO REGION VALUES(2,'Tarapacá');
INSERT INTO REGION VALUES(3,'Antofagasta');
INSERT INTO REGION VALUES(4,'Atacama');
INSERT INTO REGION VALUES(5,'Coquimbo');
INSERT INTO REGION VALUES(6,'Valparaíso');
INSERT INTO REGION VALUES(7,'Metropolitana de Santiago');
INSERT INTO REGION VALUES(8,'Libertador General Bernardo O’Higgins');
INSERT INTO REGION VALUES(9,'Maule');
INSERT INTO REGION VALUES(10,'Ñuble');
INSERT INTO REGION VALUES(11,'Biobío');
INSERT INTO REGION VALUES(12,'La Araucanía');
INSERT INTO REGION VALUES(13,'Los Ríos');
INSERT INTO REGION VALUES(14,'Los Lagos');
INSERT INTO REGION VALUES(15,'Aysén del General Carlos Ibáñez del Campo');
INSERT INTO REGION VALUES(16,'Magallanes y Antártica Chilena');

CREATE TABLE COMUNA
(
    ID_COMUNA NUMBER (10),
    NOMBRE_COMUNA VARCHAR2 (50) NOT NULL,
    ID_REGION NUMBER (10),
    CONSTRAINT COMUNA_pk PRIMARY KEY (ID_COMUNA)
);

--COMUNAS
INSERT ALL 
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(1,'Arica',1)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(2,'Camarones',1)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(3,'General Lagos',1)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(4,'Putre',1)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(5,'Alto Hospicio',2)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(6,'Iquique',2)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(7,'Camiña',2)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(8,'Colchane',2)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(9,'Huara',2)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(10,'Pica',2)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(11,'Pozo Almonte',2)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(12,'Antofagasta',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(13,'Mejillones',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(14,'Sierra Gorda',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(15,'Taltal',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(16,'Calama',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(17,'Ollague',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(18,'San Pedro de Atacama',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(19,'María Elena',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(20,'Tocopilla',3)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(21,'Chañaral',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(22,'Diego de Almagro',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(23,'Caldera',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(24,'Copiapó',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(25,'Tierra Amarilla',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(26,'Alto del Carmen',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(27,'Freirina',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(28,'Huasco',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(29,'Vallenar',4)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(30,'Canela',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(31,'Illapel',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(32,'Los Vilos',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(33,'Salamanca',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(34,'Andacollo',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(35,'Coquimbo',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(36,'La Higuera',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(37,'La Serena',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(38,'Paihuaco',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(39,'Vicuña',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(40,'Combarbalá',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(41,'Monte Patria',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(42,'Ovalle',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(43,'Punitaqui',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(44,'Río Hurtado',5)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(45,'Isla de Pascua',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(46,'Calle Larga',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(47,'Los Andes',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(48,'Rinconada',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(49,'San Esteban',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(50,'La Ligua',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(51,'Papudo',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(52,'Petorca',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(53,'Zapallar',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(54,'Hijuelas',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(55,'La Calera',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(56,'La Cruz',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(57,'Limache',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(58,'Nogales',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(59,'Olmué',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(60,'Quillota',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(61,'Algarrobo',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(62,'Cartagena',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(63,'El Quisco',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(64,'El Tabo',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(65,'San Antonio',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(66,'Santo Domingo',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(67,'Catemu',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(68,'Llaillay',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(69,'Panquehue',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(70,'Putaendo',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(71,'San Felipe',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(72,'Santa María',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(73,'Casablanca',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(74,'Concón',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(75,'Juan Fernández',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(76,'Puchuncaví',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(77,'Quilpué',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(78,'Quintero',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(79,'Valparaíso',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(80,'Villa Alemana',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(81,'Viña del Mar',6)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(82,'Colina',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(83,'Lampa',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(84,'Tiltil',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(85,'Pirque',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(86,'Puente Alto',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(87,'San José de Maipo',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(88,'Buin',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(89,'Calera de Tango',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(90,'Paine',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(91,'San Bernardo',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(92,'Alhué',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(93,'Curacaví',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(94,'María Pinto',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(95,'Melipilla',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(96,'San Pedro',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(97,'Cerrillos',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(98,'Cerro Navia',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(99,'Conchalí',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(100,'El Bosque',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(101,'Estación Central',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(102,'Huechuraba',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(103,'Independencia',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(104,'La Cisterna',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(105,'La Granja',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(106,'La Florida',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(107,'La Pintana',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(108,'La Reina',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(109,'Las Condes',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(110,'Lo Barnechea',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(111,'Lo Espejo',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(112,'Lo Prado',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(113,'Macul',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(114,'Maipú',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(115,'Ñuñoa',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(116,'Pedro Aguirre Cerda',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(117,'Peñalolén',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(118,'Providencia',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(119,'Pudahuel',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(120,'Quilicura',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(121,'Quinta Normal',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(122,'Recoleta',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(123,'Renca',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(124,'San Miguel',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(125,'San Joaquín',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(126,'San Ramón',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(127,'Santiago',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(128,'Vitacura',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(129,'El Monte',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(130,'Isla de Maipo',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(131,'Padre Hurtado',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(132,'Peñaflor',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(133,'Talagante',7)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(134,'Codegua',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(135,'Coínco',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(136,'Coltauco',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(137,'Doñihue',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(138,'Graneros',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(139,'Las Cabras',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(140,'Machalí',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(141,'Malloa',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(142,'Mostazal',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(143,'Olivar',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(144,'Peumo',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(145,'Pichidegua',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(146,'Quinta de Tilcoco',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(147,'Rancagua',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(148,'Rengo',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(149,'Requínoa',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(150,'San Vicente de Tagua Tagua',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(151,'La Estrella',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(152,'Litueche',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(153,'Marchihue',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(154,'Navidad',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(155,'Peredones',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(156,'Pichilemu',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(157,'Chépica',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(158,'Chimbarongo',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(159,'Lolol',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(160,'Nancagua',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(161,'Palmilla',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(162,'Peralillo',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(163,'Placilla',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(164,'Pumanque',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(165,'San Fernando',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(166,'Santa Cruz',8)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(167,'Cauquenes',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(168,'Chanco',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(169,'Pelluhue',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(170,'Curicó',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(171,'Hualañé',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(172,'Licantén',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(173,'Molina',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(174,'Rauco',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(175,'Romeral',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(176,'Sagrada Familia',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(177,'Teno',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(178,'Vichuquén',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(179,'Colbún',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(180,'Linares',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(181,'Longaví',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(182,'Parral',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(183,'Retiro',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(184,'San Javier',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(185,'Villa Alegre',9)
  INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(186,'Yerbas Buenas',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(187,'Constitución',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(188,'Curepto',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(189,'Empedrado',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(190,'Maule',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(191,'Pelarco',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(192,'Pencahue',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(193,'Río Claro',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(194,'San Clemente',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(195,'San Rafael',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(196,'Talca',9)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(197,'Bulnes',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(198,'Chillán',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(199,'Chillán Viejo',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(200,'Cobquecura',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(201,'Coelemu',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(202,'Coihueco',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(203,'El Carmen',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(204,'Ninhue',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(205,'Ñiquen',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(206,'Pemuco',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(207,'Pinto',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(208,'Portezuelo',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(209,'Quirihue',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(210,'Ránquil',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(211,'Treguaco',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(212,'Quillón',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(213,'San Carlos',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(214,'San Fabián',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(215,'San Ignacio',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(216,'San Nicolás',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(217,'Yungay',10)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(218,'Arauco',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(219,'Cañete',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(220,'Contulmo',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(221,'Curanilahue',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(222,'Lebu',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(223,'Los Álamos',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(224,'Tirúa',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(225,'Alto Biobío',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(226,'Antuco',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(227,'Cabrero',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(228,'Laja',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(229,'Los Ángeles',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(230,'Mulchén',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(231,'Nacimiento',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(232,'Negrete',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(233,'Quilaco',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(234,'Quilleco',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(235,'San Rosendo',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(236,'Santa Bárbara',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(237,'Tucapel',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(238,'Yumbel',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(239,'Chiguayante',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(240,'Concepción',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(241,'Coronel',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(242,'Florida',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(243,'Hualpén',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(244,'Hualqui',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(245,'Lota',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(246,'Penco',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(247,'San Pedro de La Paz',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(248,'Santa Juana',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(249,'Talcahuano',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(250,'Tomé',11)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(251,'Carahue',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(252,'Cholchol',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(253,'Cunco',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(254,'Curarrehue',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(255,'Freire',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(256,'Galvarino',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(257,'Gorbea',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(258,'Lautaro',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(259,'Loncoche',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(260,'Melipeuco',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(261,'Nueva Imperial',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(262,'Padre Las Casas',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(263,'Perquenco',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(264,'Pitrufquén',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(265,'Pucón',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(266,'Saavedra',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(267,'Temuco',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(268,'Teodoro Schmidt',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(269,'Toltén',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(270,'Vilcún',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(271,'Villarrica',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(272,'Angol',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(273,'Collipulli',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(274,'Curacautín',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(275,'Ercilla',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(276,'Lonquimay',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(277,'Los Sauces',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(278,'Lumaco',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(279,'Purén',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(280,'Renaico',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(281,'Traiguén',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(282,'Victoria',12)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(283,'Corral',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(284,'Lanco',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(285,'Los Lagos',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(286,'Máfil',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(287,'Mariquina',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(288,'Paillaco',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(289,'Panguipulli',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(290,'Valdivia',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(291,'Futrono',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(292,'La Unión',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(293,'Lago Ranco',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(294,'Río Bueno',13)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(295,'Ancud',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(296,'Castro',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(297,'Chonchi',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(298,'Curaco de Vélez',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(299,'Dalcahue',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(300,'Puqueldón',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(301,'Queilén',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(302,'Quemchi',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(303,'Quellón',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(304,'Quinchao',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(305,'Calbuco',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(306,'Cochamó',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(307,'Fresia',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(308,'Frutillar',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(309,'Llanquihue',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(310,'Los Muermos',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(311,'Maullín',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(312,'Puerto Montt',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(313,'Puerto Varas',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(314,'Osorno',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(315,'Puero Octay',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(316,'Purranque',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(317,'Puyehue',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(318,'Río Negro',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(319,'San Juan de la Costa',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(320,'San Pablo',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(321,'Chaitén',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(322,'Futaleufú',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(323,'Hualaihué',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(324,'Palena',14)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(325,'Aisén',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(326,'Cisnes',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(327,'Guaitecas',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(328,'Cochrane',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(329,'O higgins',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(330,'Tortel',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(331,'Coihaique',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(332,'Lago Verde',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(333,'Chile Chico',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(334,'Río Ibáñez',15)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(335,'Antártica',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(336,'Cabo de Hornos',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(337,'Laguna Blanca',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(338,'Punta Arenas',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(339,'Río Verde',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(340,'San Gregorio',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(341,'Porvenir',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(342,'Primavera',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(343,'Timaukel',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(344,'Natales',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(345,'Torres del Paine',16)INTO COMUNA (ID_COMUNA, NOMBRE_COMUNA, ID_REGION)VALUES
	(346,'Cabildo',6)
  SELECT * FROM dual;


  CREATE TABLE Direccion
(
    id_Direccion NUMBER (10),
    ID_COMUNA NUMBER,
	ID_REGION NUMBER,
	CALLE VARCHAR2 (50) NOT NULL,
	NUMERACION NUMBER,
    CONSTRAINT direc_pk PRIMARY KEY (id_Direccion)
);

    INSERT INTO Direccion (id_Direccion, ID_COMUNA, ID_REGION,CALLE,NUMERACION)VALUES
	(1,1,1,'Oscar Quina',1215);
	INSERT INTO Direccion (id_Direccion, ID_COMUNA, ID_REGION,CALLE,NUMERACION)VALUES
	(2,1,1,'El salvador ',1235);
	INSERT INTO Direccion (id_Direccion, ID_COMUNA, ID_REGION,CALLE,NUMERACION)VALUES
	(3,1,1,'Renato Rocca',1243);
	INSERT INTO Direccion (id_Direccion, ID_COMUNA, ID_REGION,CALLE,NUMERACION)VALUES
	(4,1,1,'Real Amada',1251);